services:
    mosquitto:
        image: eclipse-mosquitto
        container_name: mosquitto_broker
        environment: 
            TZ: Europe/Copenhagen
        volumes:
            - ./config:/mosquitto/config
            - ./data:/mosquitto/data
            - ./log:/mosquitto/log
        restart: always
        ports:
        - 1883:1883
        - 9001:9001
        stdin_open: true
        tty: true
        healthcheck:
            test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3"]
            interval: 45s
            timeout: 10s
            retries: 3
            start_period: 15s
    
    script_addtodb:
        build:
            context: .
            dockerfile: addtoDB.Dockerfile
        restart: always
        environment: 
            TZ: Europe/Copenhagen
        container_name: addMQTTtoDB
        depends_on:
            mosquitto:
                condition: service_healthy
        volumes: 
            - ./:/MQTT_database_script/
        command: ["sh", "-c", "/MQTT_database_script/script/addmqtttemptodb.sh"]
    
    node-red:
        image: nodered/node-red:latest
        container_name: node-red
        environment: 
            TZ: Europe/Copenhagen
        ports:
          - 1880:1880
        volumes:
          - ./node-red-data:/data
          - ./:/MQTT_database_script/
    
    #~ threshold_LED:
        #~ image: navikey/raspbian-buster:latest
        #~ build:
            #~ context: .
            #~ dockerfile: threshold_LED.Dockerfile
            #~ privileged: true
        #~ environment: 
            #~ TZ: Europe/Copenhagen
        #~ restart: always
        #~ container_name: threshold_LED
        #~ working_dir: /MQTT_database_script/
        #~ volumes:    
          #~ - type: bind
            #~ source: ./
            #~ target: /MQTT_database_script/
            
        #~ command: ["python3", "threshold_LED.py"]

